### ISSUE TITLE
pyARD does not handle "XX" codes

### ISSUE THREAD

**Issue by lgragert-nmdp** [nmdp-bioinformatics/pyARD#13]
Module should either handle XX codes or throw an error that gives instructions on how to do conversion with MAC service.

>>> gl = ard.redux_gl("A*01:AB","g")
>>> gl
'A*01:01/A*01:02'
>>> gl = ard.redux_gl("A*01:XX","g")
>>> gl

**Comment by mhalagan-nmdp** [comment]
#17  
[0.0.10](https://pypi.org/project/pyard/)
