### ISSUE TITLE
Implement smartsort for GL strings

### ISSUE THREAD

**Issue by lgragert-nmdp** [nmdp-bioinformatics/pyARD#14]
ard.redux_gl should not reorders GL strings entirely in alphanumerical order. 2nd field should be sorted numerically independently from 1st field.

ac = "A*01:XX"
url = "https://hml.nmdp.org/mac/api/decode?typing="
response = requests.get(url + ac)
gl = response.text
gl_ars = ard.redux_gl(gl,'g')

print (gl)
print (gl_ars)

GL Service output for A*01:XX

A*01:01/A*01:02/A*01:03/A*01:04N/A*01:06/A*01:07/A*01:08/A*01:09/A*01:10/A*01:11N/A*01:12/A*01:13/A*01:14/A*01:15N/A*01:16N/A*01:17/A*01:18N/A*01:19/A*01:20/A*01:21/A*01:22N/A*01:23/A*01:24/A*01:25/A*01:26/A*01:27N/A*01:28/A*01:29/A*01:30/A*01:31N/A*01:32/A*01:33/A*01:35/A*01:36/A*01:37/A*01:38/A*01:39/A*01:40/A*01:41/A*01:42/A*01:43/A*01:44/A*01:45/A*01:46/A*01:47/A*01:48/A*01:49/A*01:50/A*01:51/A*01:52N/A*01:53N/A*01:54/A*01:55/A*01:56N/A*01:57N/A*01:58/A*01:59/A*01:60/A*01:61/A*01:62/A*01:63/A*01:64/A*01:65/A*01:66/A*01:67/A*01:68/A*01:69/A*01:70/A*01:71/A*01:72/A*01:73/A*01:74/A*01:75/A*01:76/A*01:77/A*01:78/A*01:79/A*01:80/A*01:81/A*01:82/A*01:83/A*01:84/A*01:85/A*01:86/A*01:87N/A*01:88/A*01:89/A*01:90/A*01:91/A*01:92/A*01:93/A*01:94/A*01:95/A*01:96/A*01:97/A*01:98/A*01:99/A*01:100/A*01:101/A*01:102/A*01:103/A*01:104/A*01:105/A*01:106/A*01:107/A*01:108/A*01:109/A*01:110/A*01:111/A*01:112/A*01:113/A*01:114/A*01:115/A*01:116/A*01:117/A*01:118/A*01:119/A*01:120/A*01:121/A*01:122/A*01:123N/A*01:124/A*01:125/A*01:126/A*01:127/A*01:128/A*01:129/A*01:130/A*01:131/A*01:132/A*01:133/A*01:134/A*01:135/A*01:136/A*01:137/A*01:138/A*01:139/A*01:140/A*01:141/A*01:142/A*01:143/A*01:144/A*01:145/A*01:146/A*01:147Q/A*01:148/A*01:149/A*01:150/A*01:151/A*01:152/A*01:153/A*01:154/A*01:155/A*01:156/A*01:157/A*01:158/A*01:159/A*01:160N/A*01:161/A*01:162N/A*01:163/A*01:164/A*01:165/A*01:166/A*01:167/A*01:168/A*01:169/A*01:170/A*01:171/A*01:172/A*01:173/A*01:174/A*01:175/A*01:176/A*01:177/A*01:178N/A*01:179N/A*01:180/A*01:181/A*01:182/A*01:183/A*01:184/A*01:185/A*01:186N/A*01:187/A*01:188/A*01:189/A*01:190/A*01:191/A*01:192/A*01:193/A*01:194/A*01:195/A*01:196/A*01:197/A*01:198/A*01:199/A*01:200/A*01:201/A*01:202/A*01:203/A*01:204/A*01:205/A*01:206/A*01:207/A*01:208Q/A*01:209/A*01:210/A*01:211/A*01:212/A*01:213/A*01:214/A*01:215/A*01:216/A*01:217/A*01:218/A*01:219/A*01:220/A*01:221/A*01:222/A*01:223/A*01:224/A*01:225/A*01:226/A*01:227/A*01:228Q/A*01:229/A*01:230/A*01:231/A*01:232/A*01:233/A*01:234/A*01:235/A*01:236/A*01:237/A*01:238/A*01:239/A*01:240N/A*01:241/A*01:242/A*01:243/A*01:244/A*01:245/A*01:246/A*01:247N/A*01:248Q/A*01:249/A*01:250N/A*01:251/A*01:252/A*01:253/A*01:254/A*01:255/A*01:256/A*01:257/A*01:258N/A*01:259/A*01:260/A*01:261

Output from ard.redux_gl

A*01:01/A*01:02/A*01:03/A*01:04N/A*01:06/A*01:07/A*01:08/A*01:09/A*01:10/A*01:100/A*01:101/A*01:102/A*01:103/A*01:104/A*01:105/A*01:106/A*01:107/A*01:108/A*01:109/A*01:110/A*01:111/A*01:112/A*01:113/A*01:114/A*01:115/A*01:116/A*01:117/A*01:118/A*01:119/A*01:11N/A*01:12/A*01:120/A*01:121/A*01:122/A*01:123N/A*01:124/A*01:125/A*01:126/A*01:127/A*01:128/A*01:129/A*01:13/A*01:130/A*01:131/A*01:132/A*01:133/A*01:134/A*01:135/A*01:136/A*01:137/A*01:138/A*01:139/A*01:14/A*01:140/A*01:141/A*01:142/A*01:143/A*01:144/A*01:145/A*01:146/A*01:147Q/A*01:148/A*01:149/A*01:150/A*01:151/A*01:152/A*01:153/A*01:154/A*01:155/A*01:156/A*01:157/A*01:158/A*01:159/A*01:15N/A*01:160N/A*01:161/A*01:162N/A*01:163/A*01:164/A*01:165/A*01:166/A*01:167/A*01:168/A*01:169/A*01:16N/A*01:17/A*01:170/A*01:171/A*01:172/A*01:173/A*01:174/A*01:175/A*01:176/A*01:177/A*01:178N/A*01:179N/A*01:180/A*01:181/A*01:182/A*01:183/A*01:184/A*01:185/A*01:186N/A*01:187/A*01:188/A*01:189/A*01:18N/A*01:19/A*01:190/A*01:191/A*01:192/A*01:193/A*01:194/A*01:195/A*01:196/A*01:197/A*01:198/A*01:199/A*01:20/A*01:200/A*01:201/A*01:202/A*01:203/A*01:204/A*01:205/A*01:206/A*01:207/A*01:208Q/A*01:209/A*01:21/A*01:210/A*01:211/A*01:212/A*01:213/A*01:214/A*01:215/A*01:216/A*01:217/A*01:218/A*01:219/A*01:220/A*01:221/A*01:222/A*01:223/A*01:224/A*01:225/A*01:226/A*01:227/A*01:228Q/A*01:229/A*01:22N/A*01:23/A*01:230/A*01:231/A*01:232/A*01:233/A*01:234/A*01:235/A*01:236/A*01:237/A*01:238/A*01:239/A*01:24/A*01:240N/A*01:241/A*01:242/A*01:243/A*01:244/A*01:245/A*01:246/A*01:247N/A*01:248Q/A*01:249/A*01:25/A*01:250N/A*01:251/A*01:252/A*01:253/A*01:254/A*01:255/A*01:256/A*01:257/A*01:258N/A*01:259/A*01:26/A*01:260/A*01:261/A*01:27N/A*01:28/A*01:29/A*01:30/A*01:31N/A*01:32/A*01:33/A*01:35/A*01:36/A*01:37/A*01:38/A*01:39/A*01:40/A*01:41/A*01:42/A*01:43/A*01:44/A*01:45/A*01:46/A*01:47/A*01:48/A*01:49/A*01:50/A*01:51/A*01:52N/A*01:53N/A*01:54/A*01:55/A*01:56N/A*01:57N/A*01:58/A*01:59/A*01:60/A*01:61/A*01:62/A*01:63/A*01:64/A*01:65/A*01:66/A*01:67/A*01:68/A*01:69/A*01:70/A*01:71/A*01:72/A*01:73/A*01:74/A*01:75/A*01:76/A*01:77/A*01:78/A*01:79/A*01:80/A*01:81/A*01:82/A*01:83/A*01:84/A*01:85/A*01:86/A*01:87N/A*01:88/A*01:89/A*01:90/A*01:91/A*01:92/A*01:93/A*01:94/A*01:95/A*01:96/A*01:97/A*01:98/A*01:99

**Comment by mhalagan-nmdp** [comment]
#17  
[https://pypi.org/project/pyard/](0.0.10)
